acms-react-app/src/Pages/Admin_Pages/CustomerDetails_Page/CustomerDetails.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/businesslayer/CustomerAccountService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/businesslayer/CustomerAccountServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/datalayer/CustomerAccountRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/presentationlayer/CustomerAccountController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/presentationlayer/CustomerAccountResponseModel.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/FrontEndTesting.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/businesslayer/CustomerAccountServiceImplTest.java

Jira ticket: https://champlainsaintlambert.atlassian.net/browse/ACMS-29
Added update function for customers for admin page. fully tested back-end and front-end.
The UI didn't really change, the functionality is there now when you change the input fields and press save.
Feel free to leave a review.

feat(ACMS-CAM-29): Implement updateCustomerById (FULL STACK)

---

acms-react-app/src/Components/Navigation_Bars/Sidebar/Sidebar.css
acms-react-app/src/Pages/Admin_Pages/CustomerDetails_Page/CustomerDetails.css
acms-react-app/src/Pages/Admin_Pages/CustomerDetails_Page/CustomerDetails.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/businesslayer/CustomerAccountService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/businesslayer/CustomerAccountServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/presentationlayer/CustomerAccountController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/businesslayer/VehicleService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/businesslayer/VehicleServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/datalayer/VehicleRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/presentationlayer/VehicleController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/FrontEndTesting.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/businesslayer/CustomerAccountServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/presentationlayer/CustomerAccountControllerIntegrationTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/presentationlayer/CustomerAccountControllerUnitTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/businesslayer/VehicleServiceImplTest.java

Jira ticket: https://champlainsaintlambert.atlassian.net/browse/ACMS-30
Changes:
- Added the delete customer function
- Also deletes the vehicles that are associated to that customer
- Did all the tests for both the back-end and the front-end
- Added the controller testing for update that I had forgotten to add
UI:
**BEFORE:**
**AFTER:**

feat(ACMS-CAM-30): Implement_Frontend_With_Delete_Customer

---

ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java
diagrams/Template01_StateSequenceDiagram.puml
diagrams/Template02_DesignLevelClassDiagram.puml
diagrams/Template03_DesignLevelInteractionDiagram.puml
diagrams/Template04_StateTransitionDiagram.puml
diagrams/Template05_IntegratedDesignClassDiagram.puml

This ticket pertains to fixing a bug in the selenium testing since request model update. Also added diagramming templates to reference for documentation.
- updated selenium test
- added diagramming template

bug(acms-vm-27): updated selenium test and added templates

---

acms-react-app/src/Pages/Admin_Pages/CustomerVehicleDetails_Page/CustomerVehicleDetails.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customeraccountsmanagementsubdomain/businesslayer/CustomerAccountService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/businesslayer/VehicleService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/businesslayer/VehicleServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/presentationlayer/VehicleController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/businesslayer/VehicleServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/vehiclemanagementsubdomain/presentationlayer/VehicleControllerUnitTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

https://champlainsaintlambert.atlassian.net/browse/ACMS-21
This ticket pertains to implementing the delete customer vehicle by id  functionality.
- deleteVehicleByVehicleId() method logic implemented in the back-end
- positive and negative test cases implemented in the back-end (returning proper ResponseEntities)
- Selenium testing
- React.js front-end for CustomerVehicleDetails view modifications
After changes:

feat(acms-vm-21): delete vehicle by id

---

pull_request_template.md

doc(acms-setup-62): pull request template

---

acms-react-app/src/App.js
acms-react-app/src/Pages/Admin_Pages/Appointments_Page/Appointments.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/datalayer/AppointmentRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/datalayer/AppointmentRepositoryTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentControllerIntegrationTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentControllerUnitTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java
diagrams/Vehicles/deleteVehicleById/DeleteVehicleClassDiagram.PUML

https://champlainsaintlambert.atlassian.net/browse/ACMS-59?atlOrigin=eyJpIjoiNTdlNmEwOGU3MzgwNGIyNzgxYWE0M2JmMzlhNGNmYTUiLCJwIjoiaiJ9
Implemented functionality where when admin sees a list of appointments and their status. If a customer cancels their appointment, a button automatically is made visible and admin can delete all canceled appointments. 
- deleteAllCancelledAppointments method back-end functionality 
- deleteAllCancelledAppointments method front-end functionality 
- deleteAllCancelledAppointments end to end testing 
After Changes:

feat(acms-appm-59): delete all cancelled appointments

---

diagrams/Authentication/JavaSpringVerification/AuthorizationDesignLevelSequenceDiagram.puml
diagrams/Authentication/JavaSpringVerification/AuthorizationSystemLevelSequenceDiagram.puml
diagrams/Authentication/Login/LoginDesignLevelSequenceDiagram.puml
diagrams/Authentication/Login/LoginSystemLevelSequenceDiagram.puml
diagrams/Authentication/SignUp/SignUpDesignLevelSequenceDiagram.puml
diagrams/Authentication/SignUp/SignUpSystemLevelSequenceDiagram.puml

https://champlainsaintlambert.atlassian.net/browse/ACMS-55
Just added some missing documentation for our following sprint review

doc(ACMS-AUTH-55): Adding missing doccumentation for oAuth and next sprint

---

acms-react-app/src/Pages/Admin_Pages/AppointmentNew_Page/Calendar.js
acms-react-app/src/Pages/Admin_Pages/AppointmentNew_Page/CustomerInfo.js
acms-react-app/src/Pages/Admin_Pages/AppointmentNew_Page/ServiceList.js
acms-react-app/src/Pages/Admin_Pages/AppointmentNew_Page/TimeSlots.js
acms-react-app/src/Pages/Admin_Pages/Appointments_Page/Appointments.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/datalayer/Appointment.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentRequestModel.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentResponseModel.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentControllerUnitTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

[TICKET](https://champlainsaintlambert.atlassian.net/jira/software/projects/ACMS/boards/61/backlog?selectedIssue=ACMS-15)
This PR is related to the functionality to add a new appointment to a customers account 
- Back end methods 
- Back end tests
- Front end components and api calls
- Front end tests 
- no UI
After Changes:
- UI tweaks may need to be added later

feat(acms-appm-15): Create New Appointment

---

acms-react-app/package-lock.json
acms-react-app/package.json
acms-react-app/src/App.js
acms-react-app/src/Components/DateTimePicker/CustomDateTimePicker.js
acms-react-app/src/Components/DateTimePicker/DatePickerCss.css
acms-react-app/src/Components/Navigation_Bars/Logged_In/NavBar.js
acms-react-app/src/Pages/Admin_Pages/AppointmentSpecifics_Page/AppointmentSpecifics.js
acms-react-app/src/Pages/Admin_Pages/Appointments_Page/Appointments.js
acms-react-app/src/Pages/Admin_Pages/CustomerAppointmentDetails_Page/CustomerAppointmentDetails.js
acms-react-app/src/Pages/Admin_Pages/CustomerAppointmentNew_Page/CustomerCalendar.js
acms-react-app/src/Pages/Admin_Pages/CustomerAppointmentNew_Page/VehicleSelect.js
acms-react-app/src/Pages/Admin_Pages/CustomerAppointments_Page/CustomerAppointments.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentControllerIntegrationTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentControllerUnitTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

(link)
(sentence description)
- (changes made listed in point form)
(images)
After Changes:
(images)
(any specifications that may be useful)
(link to related pr if necessary)

feat(acms-appm-16): update appointment by appointment

---

diagrams/design class diagrams/AuthenticationDesignLevelClassDiagram.puml

Added Class Diagram for authentication

doc(ACMS-AUTH-55): added class diagram for authentication

---

ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/authenticationsubdomain/businesslayer/TokenServiceImplTest.java
diagrams/design class diagrams/integrated class diagrams/ACMSIntegratedDesignLevelClassDiagramSprint04.puml

Updated integrate class diagram

doc/(ACMS): integrated class diagram sprint 4

---

Procfile

[link](https://champlainsaintlambert.atlassian.net/jira/software/projects/ACMS/boards/61/backlog?selectedIssue=ACMS-65)
- this is a test pr to add a file to main in order to deploy the java back end

testing Heroku for CI/CD

---

acms-react-app/src/App.js
acms-react-app/src/Components/Navigation_Bars/Sidebar/Sidebar.js
acms-react-app/src/Pages/Admin_Pages/Customers/CustomerInvoices_Page/CustomerInvoiceBlock.js
acms-react-app/src/Pages/Admin_Pages/Customers/CustomerInvoices_Page/CustomerInvoices.js
acms-react-app/src/Services/admin.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/dataLayer/User.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/datalayer/CustomerInvoice.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/datalayer/CustomerInvoiceRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/presentationlayer/CustomerInvoiceController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/presentationlayer/CustomerInvoiceControllerIntegrationTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

([link](https://champlainsaintlambert.atlassian.net/browse/ACMS-24))
This ticket pertains to implementing the getAllInvoicesByCustomerId() functionality.
- getAllInvoicesByCustomerId method logic implemented in the back-end
- positive and negative test cases implemented in the back-end (returning proper ResponseEntities)
- Selenium testing
-   React.js front-end for Customer Invoices view (Admin and Customer)
After Changes:

feat(acms-inv-24): view all invoices by customerId

---

acms-react-app/src/App.js
acms-react-app/src/Pages/Admin_Pages/Customers/CustomerInvoices_Page/CustomerInvoices.js
acms-react-app/src/Pages/Admin_Pages/Invoices/Invoices_Page/AddNewInvoice.js
acms-react-app/src/Services/admin.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/presentationlayer/CustomerInvoiceController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/presentationlayer/CustomerInvoiceControllerIntegrationTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

([link](https://champlainsaintlambert.atlassian.net/browse/ACMS-23))
This ticket pertains to implementing the addInvoiceToCustomerAccount() functionality.
- addInvoiceToCustomerAccount() method logic implemented in the back-end
- positive and negative test cases implemented in the back-end (returning proper ResponseEntities)
- Selenium testing
- React.js front-end for New Invoice view (Admin)
After Changes:
- Made it so that invoices can only be created for confirmed customer appointments
- Will implement an automatic status change to 'COMPLETED' for appointments that have a corresponding invoice created in future pr
[(link to related pr if necessary)](https://champlainsaintlambert.atlassian.net/browse/ACMS-80)

feat(acms-inv-23): create new invoice

---

acms-react-app/src/App.js
acms-react-app/src/Pages/Admin_Pages/Invoices/Invoices_Page/InvoiceBlock.js
acms-react-app/src/Pages/Admin_Pages/Invoices/Invoices_Page/InvoiceDeails.js
acms-react-app/src/Pages/Admin_Pages/Invoices/Invoices_Page/Invoices.js
acms-react-app/src/Services/admin.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/datalayer/CustomerInvoiceRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/presentationlayer/CustomerInvoiceController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/presentationlayer/CustomerInvoiceControllerIntegrationTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

[(link)](https://champlainsaintlambert.atlassian.net/jira/software/projects/ACMS/boards/61/backlog?selectedIssue=ACMS-77)
This story is to have the functionality to click on an invoice and a form pops up displaying the details of that invoice.
- Made Invoice rows clickable
- Made a new UI for Invoice details
- Back end methods
- Back end testing 
- Front end testing

feat(acms-inv-77): get invoice details

---

ateliermecanique-ws/src/main/resources/schema-h2.sql

(link)
(sentence description)
- (changes made listed in point form)
(images)
After Changes:
(images)
(any specifications that may be useful)
(link to related pr if necessary)

database syntax fix

---

.github/workflows/main.yml

[(link)](https://champlainsaintlambert.atlassian.net/jira/software/projects/ACMS/boards/61/backlog?selectedIssue=ACMS-65)
This pr is re,ated to make back end test run and all pass before allowing to be merged into main
- Added main.yml file

conf(ACMS-SETUP-65) Added Github Actions to Run Backend Tests

---

acms-react-app/src/Pages/Admin_Pages/Appointments/AppointmentNew_Page/TimeSlots.js
acms-react-app/src/Services/customer.service.js
acms-react-app/src/Services/user.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/presentationlayer/CustomerInvoiceController.java
diagrams/2-customer/Mailer/RegistrationEmailDesignDiagram.puml
diagrams/2-customer/Mailer/RegistrationEmailSystemDiagram.puml
diagrams/Authentication/Login/LoginDesignLevelSequenceDiagram.puml
diagrams/Authentication/Login/LoginSystemLevelSequenceDiagram.puml
diagrams/Authentication/PasswordReset/PasswordResetDesignLevel.puml
diagrams/Authentication/PasswordReset/PasswordResetSystemLevel.puml
diagrams/C4/C4l3APIECP.puml
diagrams/design class diagrams/AuthenticationDesignLevelClassDiagram.puml
diagrams/design class diagrams/integrated class diagrams/ACMSIntegratedDesignLevelClassDiagramSprint04.puml

Added c4 diagrams and system and design level diagrams as well as class diagrams for sprint 4 and 5.

diag(ACMS-AUTH): Diagrams

---

acms-react-app/src/Pages/Admin_Pages/Invoices/Invoices_Page/InvoiceDeails.js
acms-react-app/src/Services/admin.service.js

(link)
(sentence description)
- (changes made listed in point form)
(images)
After Changes:
(images)
(any specifications that may be useful)
(link to related pr if necessary)

Update Invoice Bug Fixed

---

acms-react-app/package-lock.json
acms-react-app/package.json
acms-react-app/src/App.js
acms-react-app/src/Pages/Admin_Pages/Reviews/Reviews_Page/Reviews.js
acms-react-app/src/Pages/Admin_Pages/Reviews/Reviews_Page/ReviewsBlock.js
acms-react-app/src/Services/admin.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/utils/security/WebSecurityConfig.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewsService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewsServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/datalayer/ReviewIdentifier.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/datalayer/Reviews.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/datalayer/ReviewsRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/datamapperlayer/ReviewRequestMapper.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/datamapperlayer/ReviewResponseMapper.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewRequestModel.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewResponseModel.java
ateliermecanique-ws/src/main/resources/data-mysql.sql
ateliermecanique-ws/src/main/resources/schema-mysql.sql
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewsServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewControllerIntegration.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

[(link)](https://champlainsaintlambert.atlassian.net/jira/software/projects/ACMS/boards/61/backlog?selectedIssue=ACMS-83)
This PR is related to adding the functionality to show all the reviews on a dashboard 
- Front end new page 
- Back end methods
- testing 100%
After Changes:

feat(ACMS-REV-83): Get All Reviews 

---

ateliermecanique-ws/build.gradle
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/presentationlayer/AppointmentController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/emailsubdomain/businesslayer/EmailService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/emailsubdomain/businesslayer/EmailServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/emailsubdomain/presentationlayer/EmailController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/emailsubdomain/presentationlayer/EmailRequest.java
ateliermecanique-ws/src/main/resources/application.properties
ateliermecanique-ws/src/main/resources/data-h2.sql
ateliermecanique-ws/src/main/resources/data-mysql.sql
ateliermecanique-ws/src/main/resources/templates/template.html
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/appointmentmanagementsubdomain/businesslayer/AppointmentServiceImplTest.java

https://champlainsaintlambert.atlassian.net/browse/ACMS-40
created the email subdomain for the email service that communicates with the appointment service when an appointment is created. Sub domain has yet to be connected to the appointment sub domain however. 
-Created EmailService
-Created EmailServiceImpl
-Created EmailRequestModel
-Created EmailResponseModel
-Created EmailController
After Changes:

feat(acms-ne-47): Send appointment confirmation email

---

acms-react-app/src/Pages/Admin_Pages/Reviews/Reviews_Page/ReviewDetails.js
acms-react-app/src/Pages/Admin_Pages/Reviews/Reviews_Page/ReviewsBlock.js
acms-react-app/src/Services/admin.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewControllerUnitTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/zelenium/FrontEndTesting.java

[(link)
](https://champlainsaintlambert.atlassian.net/jira/software/projects/ACMS/boards/61/backlog?selectedIssue=ACMS-84)
This story is to add functionality to allow a customer to update their reviews
- Added new back end methods for updating a review
- Added a button to front end form
- Backend testing
- Front end testing
After Changes:

feat(ACMS-REV-84):Update Review

---

acms-react-app/src/App.js
acms-react-app/src/Pages/Admin_Pages/Reviews/Reviews_Page/ReviewDetails.js
acms-react-app/src/Pages/Admin_Pages/Reviews/Reviews_Page/ReviewDetailsAdmin.js
acms-react-app/src/Services/admin.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/datalayer/ReviewRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewRequestModel.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/datalayer/ReviewRepositoryTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewControllerIntegration.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewControllerUnitTest.java

([link](https://champlainsaintlambert.atlassian.net/browse/ACMS-88))
This ticket pertains to implementing the function to reply to a posted review by adding comments to the response model via the mechanic account.
- back end logic
- front-end implementation
- back end testing (positive and negative cases)
- selenium tests
- Only mechanic can update the mechanic reply field in form
- Only customer can update other fields in form
https://champlainsaintlambert.atlassian.net/browse/ACMS-84

feat(acms-rev-88): Update mechanic reply 

---

acms-react-app/package-lock.json
acms-react-app/package.json
acms-react-app/src/App.js
acms-react-app/src/Pages/Login_Page/Login.js
acms-react-app/src/Pages/ResetPasswordRequest_Page/ResetPasswordRequest.js
acms-react-app/src/Pages/ResetPassword_Pages/ResetPassword.js
acms-react-app/src/Pages/ResetPassword_Pages/ResetPasswordRequest.js
acms-react-app/src/Services/auth-header.js
acms-react-app/src/Services/auth.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/dataLayer/repositories/UserRepository.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/presentationlayer/Payload/Request/ResetPasswordEmailRequest.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/presentationlayer/Payload/Request/ResetPasswordRequest.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/presentationlayer/controllers/AuthController.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/utils/security/WebSecurityConfig.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/emailsubdomain/businesslayer/EmailServiceImpl.java
ateliermecanique-ws/src/main/resources/templates/passwordReset.html
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/authenticationsubdomain/presentationlayer/AuthControllerTest.java
diagrams/Authentication/PasswordReset/PasswordResetDesignLevel.puml
diagrams/Authentication/PasswordReset/PasswordResetSystemLevel.puml
diagrams/design class diagrams/AuthenticationDesignLevelClassDiagram.puml
diagrams/design class diagrams/integrated class diagrams/ACMSIntegratedDesignClassDiagramSprint05.puml
docker-compose.yml

JIRA: https://champlainsaintlambert.atlassian.net/browse/ACMS-42
- We want users to be able to reset their password if ever they forget their password.
- A secure way to do this was to send the access token to their email as a message where they click on the link and it brings  them to our website.
- Added reset password functionality
- Added 2 other pages (request and password reset)

feat(ACMS-AUTH-42): reset password

---

acms-react-app/src/App.js
acms-react-app/src/Pages/Admin_Pages/Customers/AddNewReview_Page/AddNewReview.js
acms-react-app/src/Pages/Admin_Pages/Reviews/Reviews_Page/Reviews.js
acms-react-app/src/Services/customer.service.js
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/customerinvoicemanagementsubdomain/businesslayer/CustomerInvoiceServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewService.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewServiceImpl.java
ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewController.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/businesslayer/ReviewServiceImplTest.java
ateliermecanique-ws/src/test/java/com/champlain/ateliermecaniquews/reviewssubdomain/presentationlayer/ReviewControllerUnitTest.java

(link)
(sentence description)
- (changes made listed in point form)
(images)
After Changes:
(images)
(any specifications that may be useful)
(link to related pr if necessary)

feat(acms-rev-82): add review

---

acms-react-app/src/Components/Footer/Footer.js

testing CI/CD

---

nginx/nginx.conf

Deployment Typo Issue

---

ateliermecanique-ws/src/main/java/com/champlain/ateliermecaniquews/authenticationsubdomain/utils/security/WebSecurityConfig.java

Updating CORS
